# Generated by Django 2.1 on 2018-08-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('colors', models.CharField(choices=[('BLK', 'black'), ('WHE', 'white'), ('GRY', 'grey'), ('BRW', 'brown'), ('RED', 'red')], default='BLK', max_length=3)),
                ('age', models.IntegerField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('toy', models.CharField(blank=True, max_length=50)),
                ('mood', models.CharField(choices=[('HAY', 'happy'), ('GRY', 'grumpy'), ('BAD', 'bad'), ('MIC', 'milkholic')], default='HAY', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
